---
version: 2
jobs:
  build:
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.2.0
    working_directory: ~/cli-engine-command
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-engine-command-{{ .Branch }}-{{checksum "package.json"}}
            - cli-engine-command-{{ .Branch }}
            - cli-engine-command-master
      - run: |
          # setup yarn
          yarn --prefer-offline --pure-lockfile

          # test project
          jest --coverage
          flow check
          eslint .
          bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: cli-engine-command-{{ .Branch }}-{{checksum "package.json"}}
          paths:
            - ~/cli-engine-command/node_modules
            - /usr/local/share/.cache/yarn
      - save_cache:
          key: cli-engine-command-{{ .Branch }}
          paths:
            - /usr/local/share/.cache/yarn
